#!/usr/bin/env bash
# Create a new server block configuration file for the domain you want to redirect from
 
sudo apt update
sudo apt install nginx -y


echo "server {
    listen 80;
    listen [::]:80;
    web_01 udobeke.tech;

    location /redirect_me {
        return 301 https://udobeke.tech/https://www.youtube.com;
    }

}" | sudo tee /etc/nginx/sites-available/www.youtube.com > /dev/null
sudo ln -s /etc/nginx/sites-available/www.youtube.com /etc/nginx/sites-enabled/

sudo service nginx restart
